BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[auth_logs] (
    [id] NVARCHAR(1000) NOT NULL,
    [userId] NVARCHAR(1000),
    [username] NVARCHAR(1000),
    [action] NVARCHAR(1000) NOT NULL,
    [status] NVARCHAR(1000) NOT NULL,
    [message] NVARCHAR(1000),
    [deviceId] NVARCHAR(1000),
    [ipAddress] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [auth_logs_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [auth_logs_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
